/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#adc6ff',
        'on-primary': '#002e6a',
        'primary-container': '#005cc5',
        'on-primary-container': '#cddbff',
        secondary: '#b7c8e1',
        'on-secondary': '#213145',
        'secondary-container': '#3a4a5f',
        'on-secondary-container': '#a9bad3',
        tertiary: '#4edea3',
        'on-tertiary': '#003824',
        'tertiary-container': '#006e4b',
        'on-tertiary-container': '#67f4b7',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        surface: '#0b1326',
        'on-surface': '#dae2fd',
        'surface-dim': '#0b1326',
        'surface-bright': '#31394d',
        'surface-container-lowest': '#060e20',
        'surface-container-low': '#131b2e',
        'surface-container': '#171f33',
        'surface-container-high': '#222a3d',
        'surface-container-highest': '#2d3449',
        'surface-variant': '#2d3449',
        'on-surface-variant': '#c2c6d4',
        outline: '#8c919d',
        'outline-variant': '#424752',
        'inverse-surface': '#dae2fd',
        'inverse-on-surface': '#283044',
        'inverse-primary': '#005ac2',
        'surface-tint': '#adc6ff',
        'primary-fixed': '#d8e2ff',
        'primary-fixed-dim': '#adc6ff',
        'secondary-fixed': '#d3e4fe',
        'secondary-fixed-dim': '#b7c8e1',
        'tertiary-fixed': '#6ffbbe',
        'tertiary-fixed-dim': '#4edea3',
      },
      fontFamily: {
        sans: ['Inter', 'PingFang SC', 'Microsoft YaHei', 'sans-serif'],
      },
      borderRadius: {
        '2xl': '1rem',
        '3xl': '1.5rem',
      },
    },
  },
  plugins: [],
}
